# Generated by Django 3.2.12 on 2023-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='无名氏2245168592460', max_length=13, verbose_name='昵称'),
        ),
    ]
