# Generated by Django 3.2.12 on 2023-08-28 06:50

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, verbose_name='用户名')),
                ('account_avatar', models.TextField(blank=True, null=True, verbose_name='账号头像')),
                ('account_cookie', models.TextField(blank=True, null=True, verbose_name='账号cookie')),
                ('account_status', models.BooleanField(blank=True, default=True, verbose_name='账号登录状态')),
                ('account_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='账号类型,[活跃，静默，删除]')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('group_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='分组类型,[正常，删除]')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100, verbose_name='平台名称')),
                ('prefix_name', models.CharField(max_length=256, verbose_name='平台前缀')),
                ('platform_icon', models.CharField(max_length=256, verbose_name='平台图标')),
                ('platform_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='平台状态,[支持，删除]')),
                ('login_url', models.CharField(max_length=256, verbose_name='登录地址')),
                ('home_url', models.CharField(max_length=256, verbose_name='主页地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建事件')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('selector_name', models.CharField(max_length=256, verbose_name='选择器名称')),
                ('selector_path', models.CharField(max_length=256, verbose_name='选择器路径')),
                ('selector_type', models.CharField(max_length=256, verbose_name='选择器类型')),
                ('selector_from', models.CharField(max_length=100, verbose_name='选择器平台')),
                ('selector_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='选择器状态,[支持，删除]')),
            ],
        ),
    ]
