# Generated by Django 3.2.12 on 2023-08-28 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selector_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selector',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selector_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='own_account',
            field=models.ManyToManyField(related_name='groups', to='Account.Account'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='account_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_user', to=settings.AUTH_USER_MODEL, verbose_name='账号操作员'),
        ),
        migrations.AddField(
            model_name='account',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='from_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from_platform', to='Account.platform', verbose_name='账号平台'),
        ),
        migrations.AddField(
            model_name='account',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
