# Generated by Django 3.2.12 on 2023-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_avatar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='账号头像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
